workflows:
  ios-release:
    name: Coco iOS Release
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      flutter: 3.6.0
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - coco_appstore
        certificates:
          - coco_distribution
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.patpat.patpatGame"
        APP_STORE_APPLE_ID: 6768066404
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    scripts:
      - name: Set up keychain + signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: flutter packages get
        script: flutter packages pub get
      - name: Pod install
        script: |
          cd ios
          pod install
      - name: Bump iOS build number
        script: |
          cd ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID" || echo 0)
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build IPA (release)
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false
